name: basic_backend
description: A server app using the shelf package and Docker.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:
  api_agent: 
    path: ../../..
  args: ^2.0.0
  basic_shared: 
    path: ../basic_shared
  shelf: ^1.1.0
  shelf_router: ^1.0.0

dev_dependencies:
  http: ^0.13.0
  lints: ^1.0.0
  test_process: ^2.0.0
  test: ^1.15.0
