name: basic_backend
description: A server app using the shelf package and Docker.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  api_agent: 
    path: ../../..
  args: ^2.4.2
  basic_shared: 
    path: ../basic_shared
  shelf: ^1.4.1
  shelf_router: ^1.1.4

dev_dependencies:
  http: ^1.1.0
  lints: ^3.0.0
  test_process: ^2.1.0
  test: ^1.24.8
