name: api_agent_custom_types_example

publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  api_agent:
    path: ../../
  dart_mappable: ^1.0.0-dev.4
  shelf: ^1.1.0

dev_dependencies:
  build_runner: ^2.0.5

dependency_overrides:
  type_plus: 0.6.3