name: api_agent_custom_types_example

publish_to: none
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  api_agent:
    path: ../../
  dart_mappable: ^4.0.1
  shelf: ^1.4.1

dev_dependencies:
  build_runner: ^2.4.6
  dart_mappable_builder: ^4.0.1

dependency_overrides:
  type_plus: 0.6.3