name: api_agent
description: Generate technology-agnostic api bindings for both client and server.
version: 0.6.1
repository: https://github.com/schultek/api_agent
issue_tracker: https://github.com/schultek/api_agent/issues

dependencies:
  analyzer: ^6.3.0
  build: ^2.4.1
  collection: ^1.17.1
  dart_style: ^2.3.3
  http: ^1.1.0
  path: ^1.8.3
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  source_gen: ^1.4.0
  type_plus: ^2.1.0

dev_dependencies:
  build_runner: ^2.4.6
  lints: ^3.0.0
  test: ^1.24.8

environment:
  sdk: '>=2.12.0 <3.0.0'
