name: api_agent
description: Generate technology-agnostic api bindings for both client and server.
version: 0.1.1
repository: https://github.com/schultek/api_agent
issue_tracker: https://github.com/schultek/api_agent/issues

dependencies:
  analyzer: ^2.0.0
  build: ^2.0.0
  collection: ^1.15.0
  http: ^0.13.3
  path: ^1.8.0
  shelf: ^1.1.0
  shelf_router: ^1.1.1
  source_gen: ^1.0.5

dev_dependencies:
  build_runner: ^2.0.5
  lints: ^1.0.1
  test: ^1.17.4

environment:
  sdk: '>=2.12.0 <3.0.0'
