name: api_agent_websocket_example

publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  api_agent:
    path: ../../
  shelf: ^1.1.0
  shelf_web_socket: ^1.0.1

dev_dependencies:
  build_runner: ^2.0.5