name: api_agent_websocket_example

publish_to: none
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  api_agent:
    path: ../../
  shelf: ^1.4.1
  shelf_web_socket: ^1.0.4

dev_dependencies:
  build_runner: ^2.0.5