name: basic_shared
description: A simple command-line application.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  api_agent:
    path: ../../..

dev_dependencies:
  build_runner: ^2.1.7
  lints: ^1.0.0
